CREATE SCHEMA IF NOT EXISTS BUS;

CREATE TABLE BUS.LISTING
( LISTING_ID		INTEGER UNIQUE,
  HOST_ID			INTEGER UNIQUE,
  LOAD_DDTM			TIMESTAMP WITH TIME ZONE,
  SOURCE_ID			INTEGER,
  PRIMARY KEY(LISTING_ID,HOST_ID,LOAD_DDTM,SOURCE_ID)
);


CREATE TABLE BUS.LISTING_INFO
( LISTING_ID		INTEGER REFERENCES BUS.LISTING(LISTING_ID),
  LISTING_URL		VARCHAR,
  LISTING_NAME		VARCHAR,
  DESCRIPTION		VARCHAR,
  ROOMTYPE			VARCHAR,
  RATING			NUMERIC(23,10),
  PHOTO_URL			VARCHAR,
  NEIGHBOURHOOD		VARCHAR,
  PROPERTY_TYPE		VARCHAR,
  ZIPCODE			VARCHAR,
  BEDS				VARCHAR,
  DDTM_VALID_FROM	TIMESTAMP WITH TIME ZONE,
  DTTM_VALID_TO		TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(LISTING_ID,DDTM_VALID_FROM)
);


CREATE TABLE BUS.LISTING_PRICE
( LISTING_ID		INTEGER REFERENCES BUS.LISTING(LISTING_ID),
  PRICES			NUMERIC(23,10),
  DDTM_VALID_FROM	TIMESTAMP WITH TIME ZONE,
  DTTM_VALID_TO		TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(LISTING_ID,DDTM_VALID_FROM)
);




CREATE TABLE BUS.HOST
( HOST_ID			INTEGER UNIQUE REFERENCES BUS.LISTING(HOST_ID),
  NAME				VARCHAR,
  EMAIL				VARCHAR,
  PHONE				VARCHAR,
  HOST_SINCE		DATE,
  LOAD_DDTM			TIMESTAMP WITH TIME ZONE,
  SOURCE_ID			INTEGER,
  PRIMARY KEY(HOST_ID,LOAD_DDTM,SOURCE_ID)
);


CREATE TABLE BUS.HOST_INFO
( INFO_ID			INTEGER,
  HOST_ID			INTEGER REFERENCES BUS.HOST(HOST_ID),
  RESPONSERATE		NUMERIC(1,1),
  HOSTRATING		NUMERIC(1,1),
  DDTM_VALID_FROM	TIMESTAMP WITH TIME ZONE,
  DTTM_VALID_TO		TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(INFO_ID,DDTM_VALID_FROM)
);


CREATE TABLE BUS.REVIEWS
( REVIEW_ID			INTEGER UNIQUE,
  LISTING_ID		INTEGER REFERENCES BUS.LISTING(LISTING_ID),
  LOAD_DDTM			TIMESTAMP WITH TIME ZONE,
  SOURCE_ID			INTEGER,
  PRIMARY KEY(REVIEW_ID,LOAD_DDTM,SOURCE_ID)
);


CREATE TABLE BUS.REVIEWS_INFO
( REVIEW_ID			INTEGER REFERENCES BUS.REVIEWS(REVIEW_ID),
  REVIEWER_NAME		VARCHAR,
  COMMENTS			VARCHAR,
  DATE_PUBLICATION	DATE,
  DDTM_VALID_FROM	TIMESTAMP WITH TIME ZONE,
  DTTM_VALID_TO		TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(REVIEW_ID,DDTM_VALID_FROM)
);


CREATE TABLE BUS.CALENDAR
( LISTING_ID		INTEGER REFERENCES BUS.LISTING(LISTING_ID),
  CALENDAR_DATE		DATE,
  AVAILABLE			BOOLEAN,
  PRIMARY KEY(LISTING_ID,CALENDAR_DATE)
);


CREATE TABLE BUS.LISTING_GUEST
( LISTING_ID		INTEGER REFERENCES BUS.LISTING(LISTING_ID),
  GUEST_ID			INTEGER,
  LOAD_DDTM			TIMESTAMP WITH TIME ZONE,
  SOURCE_ID			INTEGER,
  PRIMARY KEY(LISTING_ID,GUEST_ID,LOAD_DDTM,SOURCE_ID)
);


CREATE TABLE BUS.GUEST
( GUEST_ID			INTEGER,
  NAME				VARCHAR,
  DDTM_VALID_FROM	TIMESTAMP WITH TIME ZONE,
  DTTM_VALID_TO		TIMESTAMP WITH TIME ZONE,
  PRIMARY KEY(GUEST_ID,DDTM_VALID_FROM)
);


CREATE SCHEMA IF NOT EXISTS SYSTEM;

CREATE TABLE SYSTEM.USER_LOGIN_DATA
( USER_ID			INTEGER,
  LOGINNAME			VARCHAR,
  PASSWORDHASH		VARCHAR,
  PASSWORDSALT		VARCHAR,
  HASHALGORITMID	INTEGER,
  PRIMARY KEY(USER_ID)
);

CREATE TABLE SYSTEM.HASING_ALGORITM
( HASHALGORITMID	INTEGER,
  ALGORITMNAME		VARCHAR, 
  PRIMARY KEY(HASHALGORITMID)
);