select	l.host_id,
		h.HOST_SINCE, --NEW
		li.listing_name,
		li.NEIGHBOURHOOD, -- new
		li.PROPERTY_TYPE, --new
		HI.HOSTRating,
		LI.ROOMTYPE,
		LI.ZIPCODE,--NEW
		LI.BEDS, --NEW
		R.NUMBER_REVIEWS
		LP.PRICE,
		LI.RATING
 from BUS.LISTING L
inner join BUS.LISTING_INFO LI on LI.LISTING_ID=l.LISTING_ID
left join BUS.LISTING_PRICE LP on LP.LISTING_ID=l.LISTING_ID
inner join BUS.HOST H on l.host_id = h.host_id
INNER JOIN BUS.HOST_INFO HI ON HI.host_id = H.host_id
LEFT join (SELECT LISTING_ID,COUNT(REVIEW_ID) AS NUMBER_REVIEWS FROM BUS.REVIEW GROUP BY LISTING_ID) R on l.LISTING_ID = R.LISTING_ID
